# Setup
title:        Vilma Romero
tagline:      This is about me and Statistics
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Vilma Romero
  url:        http://yourhomepage.com 

theme: jekyll-theme-cayman # to use css from the original theme
# # Gems
# gems:
#   - jekyll-paginate
#
# #Others
# markdown: kramdown

